import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Head from 'next/head'
import Footer from "@/components/Footer";

const sans = DM_Sans({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900', '1000'],
  subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dreamer ecommerce",
  description: "Generated by Dreamerwebdev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-stone-100 ${sans.className}`}>
        <Head>
          <title>Dreamer Ecommerce</title>
        </Head>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
